version: '3.7'
services:
  nginx:
    image: nginx:1.19.6-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./loyalty/frontend/dist:/usr/share/nginx/html/loyalty
      - /home/rvssn:/usr/share/nginx/html/rvssn
    command: /bin/sh -c "chown -R nginx:nginx /usr/share/nginx/html/rvssn && exec nginx -g 'daemon off;'"
    user: "nginx"
    ports:
      - 80:80
      - 443:443
    networks:
      - loyalty_default
      - rvssn_default
  portainer:
    image: portainer/portainer
    ports: 
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data

networks:
  loyalty_default:
    external: true
  rvssn_default:
    external: true