version: '3.7'
services:
  rvssn-clone:
    image: alpine/git
    volumes:
      -
  loyalty-frontend:
    build:
      context: ./loyalty/frontend
      args:
        - GIT_TOKEN=${GIT_TOKEN}
      # volumes to app/dist for nginx
    volumes:
      - ./loyalty/frontend/dist:/app/dist
    depends_on:
      - loyalty-backend
  loyalty-backend:
    build: 
      context: ./loyalty/backend
      args:
        - GIT_TOKEN=${GIT_TOKEN}
    env_file: ./loyalty/backend/.env
    volumes:
      - ./loyalty/backend:/app
  portainer:
    image: portainer/portainer
    ports: 
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data