version: '3.7'
services:
  nginx:
    image: nginx:1.19.6-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
      - 4438:443
    networks:
      - loyalty_default
      - rvssn_default
  portainer:
    image: portainer/portainer
    ports: 
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data

networks:
  loyalty_default:
    external: true
  rvssn_default:
    external: true