version: '3.7'
services:
  loyalty-frontend:
    image: node:14.15.4-alpine
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c "npm i && npm run build && chmod -R 755 ./dist && rm -rf node_modules"

  loyalty-backend:
    image: node:14.15.4-alpine
    volumes:
      - ./backend:/app
    working_dir: /app
    command: sh -c "npm i && npm start"
    env_file:
      - .env

  loyalty-finance:
    image: node:14.15.4-alpine
    volumes:
      - ./finance:/app
    working_dir: /app
    command: sh -c "npm i && npm start"
    env_file:
      - finance.env
    ports:
      - 3030:4269

  loyalty-nginx:
    image: nginx:1.19.6-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
      - ../certbot/conf:/etc/letsencrypt
      - ../certbot/www:/var/www/certbot
    depends_on:
      - loyalty-backend
    ports:
      - 8080:80
      - 4438:443

  certbot:
    image: certbot/certbot
    command: certonly --webroot -w /var/www/certbot --keep-until-expiring --agree-tos --email wacketimo@gmail.com -d loyalty.sea.hamburg -d framed.sea.hamburg -d sea.hamburg -d loyalty.timopictur.es -d framed.timopictur.es 
    volumes:
      - ../certbot/conf:/etc/letsencrypt
      - ../certbot/www:/var/www/certbot
    depends_on:
      - loyalty-nginx